== Chapter 4

By the time Bisky made it back to her apartment, the sun had only a few
minutes before it set. This was her absolute favorite time of day. She set
aside the groceries she was carrying, pulled the blinds up and opened her
window to let the calming breeze of the Cargo District come in. She had
grown accustomed to the dull roar of the ships being built and all the other
activity on the port, which took place fewer than ten short blocks away. The
distant hum was familiar and kept her company. She depended on it last week,
for sure. It was a tiny studio apartment, only about 500 square feet, so
opening the window always let in a lot of light and a lot of breeze. Living
alone sucked sometimes, but she was lucky to have found this spot. The
neighborhood wasn't _the worst_, either.

Bisky reset her attention to the groceries. She had picked up some fruits
and vegetables and a small octopus for dinner. The dish, known as _taskiak_
in Old Mephitidaean, wasn't complete without a special, sourdough bread
called _sporzo_, but she had already procured some a few days ago, when she
rid her house entirely of Petrus's baking.

Bisky enjoyed being able to cook and occasionally look to the side to glance
outside her window. It was already rather dark by the time she got to start
cooking, a fair indicator that autumn had already properly settled in.
Summers were the best, because the sun would never set. She wasn't like most
skunks when it came to that. Skunks had a reputation for staying up late and
simply preferring nighttime overall.

She picked up the big knife off of the wall and diced the octopus into small
cubes. The octupus would be lightly sautéed with plenty of lemon juice and
bay leaves, then the vegetables would be added and finally, diced sporzo
tossed in.  Bisky personally found that a splash of sunflower sauce thinned
with water also worked rather nicely on top of it all.

Bisky was in the process of adding the sauce when her portable phone rang.
She turned the phone over to discover that Rose was calling. Bisky's
eyebrows furrowed as she picked it up.

"`Hi, hello Rose.`"

"`Hello Hibiscus. How are you feeling? Is now a good time?`"

_Not really._ "`Yeah, lemme put you on speakerphone. I feel alright. I'm
cooking dinner.`"

"`Oh, what are you making?`"

"`Making myself some taskiak,`" Bisky said proudly, as she put the phone
down and picked up the chopsticks.

Rose could hear Bisky's smile through the phone. "`Good for you! A
traditional Mephitidaean treat. Where did you get the octopus?`"

"`There's a fishmonger just around the corner where I live,`" Bisky said.
_Cut to the chase, lady, whaddya want?_

"`Good, good. I wanted to talk to you about your father's business.`"

_Knew it._ "`Yup, we can do that. Oh, I wanted to thank you again about the
whole last month of rent thing... that was very generous, Rose.
Seriously.`"

"`It was the least I could do. Now, I don't want to take too much of your
time. I just wanted to talk to you about your father's assets, which are
technically all yours now...`"

Bisky already knew that to be case, but that ship didn't start to sink in
until that moment. She sat down and began to eat her meal.

"`The truth is, Hibiscus, I'm not sure if the bakery can remain as
successful as it was previously...`"

"`I think customers came for the _food_ Rose, not just the company of my
dad,`" Bisky retorted. "`You don't trust that the other guys in there will
do as good of a job?!`"

"`No, no, Hibiscus, that's not what I meant. It's _your_ business now.
_You're_ in charge of the bakery.`"

The ship sank to the bottom of the ocean. A chopstickful of taskiak fell out
of Bisky's mouth and back onto the plate with a _plop_.

"`And, well, I figured that you wouldn't have the time, nor maybe even the
inclination, to run a business full time, since that'd interfere with your
studies...`"

Bisky was struggling to keep her balance on a tightrope over precipice of
tears, but Rose kept talking. "`Is that correct? It's not within your means.
Not on a day-to-day basis.`"

Bisky swallowed, but there was no taskiak going down her thoat. "`That's
correct.`" After a brief moment of silence that felt like it lasted her
father's entire life, Bisky ventured: "`You're not.. you're not going to
force the bakery out of the building, are you?`"

Rose was audibly confused for a beat. "`Oh, goodness gracious, no! I thought
we already decided that Acanthus would pick up the slack day-to-day, even
though _on paper_ you're the beneficiary of all of your father's assets.`"

Bisky's world came back into focus. Her sigh of relief was more like gasping
for air after having been trapped underwater.

Rose continued. "`I'm filling out a bunch of forms, and I need to make sure
I'm submitting the right info. I'll make it clear to the City of Port Sokuit
that the _business_ is Acanthus's but all of Petrus's _things_ and his real
estate are yours. He didn't own any land other than the house on Seashell
Lane, right?`"

"`Yeah, that's right. We, uh, consolidated a lot of stuff when my mom
died,`" Bisky confirmed.

"`Okay. Personally, I think this will be a good arrangement. The bakery will
still be in the Damiat family, while you still get to focus on your
studies. What do you think?`"

Bisky wasn't thinking all that much. Not on purpose. "`Yeah, that's fine.
Thanks for confirming with me...`"

"`Just trying to do the right thing, Hibiscus. You know that it's important
for _me_, too, that the bakery be successful.`"

"`Right, yeah.`"

"`Well, like I said, I didn't want to take too much of your time. Enjoy your
taskiak! Take care.`"

Bisky had completely forgotten about her dinner.

"`Bye, Rose.`"

Bisky hung up the phone. She stared at her food with ambivalence. She knew
it made absolutely no sense, but she felt like there was no point in eating
immediately after a near-death experience.
