== Chapter x16 (conclusion)

Rain had finally arrived in Port Sokuit. Bisky and every other Sokuitan
believed that was rather late, the kind of late as if the rain and her gal
pals changed plans on you and didn't tell you they actually weren't going to
be there for several hours.

Bisky looked out her kitchen window, the one that let all the light in. The
overcast skies assumed a wonderful shade of slate which happened to be one
of Bisky's favorite colors.

She tended to the black, spiced tea latte she was steeping, puppeteering the
teabag with what she thought was dexterity and finesse. _I'm a
professional,_ she thought to herself, _I work at a café for crying out
loud._ She smiled briefly.

She took a bite out of her cranberry-walnut muffin. She could not remember
where this particular muffin came from. Did she make it herself? Did it come
from the Bakery Damiat? Was it sneaked into her apartment by a secret
admirer? She had no clue. It didn't really matter in the end, the muffin was
delicious and quite clearly of skunkish quality.

The tea was finally done. Wisps of steam continued to emanate from the mug.
She took a slow sip, which made a slurping noise which she didn't seem to
notice. The taste of her creation was the only important thing in this
moment. It was the only thing important thing in her entire life, in this
moment. The tea was adequately spicy. She had mixed in the perfect amount of
soymilk. Bisky marveled at herself, at her newfound energy to take pride in
the tiniest and most personal of victories.
