== Chapter x6 (in which bisky attends the 1st feralists meeting)

"`Gather round, gather round,`" the deer who looked like he was in charge
announced to everyone. His antlers alone were very large and commanding, but
he did not speak in a domineering tone at all, quite the opposite.  "`Let's
make a circle on the floor,`" the deer encouraged. He sat cross-legged where
he stood, and the dozen or so other animals followed suit. The circle was
complete. Every animal could see every other animal.

"`Thank you for coming. I see lots of new faces, that's good. I want to make
several things clear before we go any further. You are _not_ attending a
ceremony or a ritual, this an _informational meeting_ where _you_ are in
charge, _you_ get to ask the questions after I provide some basic
information about Our Faith and what we believe in. Let's have a
_discussion,_ a real back and forth. I am not here to proselytize or
otherwise sell Our Faith to you, because clearly you've already been sold
enough to come here. If you feel that I _am_ doing those things, then feel
free to interrupt me and make me aware of my errors. Also, we're not nudist
devil worshippers. Is that okay with you all?`"

There was a general consensus. Bisky already appreciated the deer's candor
and commitment to not being a jerk.

"`Alright let's begin. My name is Winter, and this is my house. Welcome. You
are here because you want to learn more about embracing _balhámotesse_ and
you are discerning a vocation in Balhámoté's name. If you're not, then you
should leave now.`"

No one left.

"`Alright. By far the most widespread misconception about balhámotesse is
that it encourages animals to become _evil_ and engage in violent or
otherwise sociopathic behavior. Actually, this is wholly contrary to what
balhámotesse _really_ is. Balhámotesse is the essence, the feeling, or
sensation of ecstasy and joy that animals feel when they prioritize
themselves and completely subject themselves to their own desires and
animalhood. Unfortunately, there are lots of other faith systems out there
which, for some reason, regard such basic, carnal, animalistic behavior as
_evil_ or somehow impure or un-virtuous. Meanwhile, we believe in a simple
'`do what you will but harm none`' philosophy. Also, Balhámoté embraces
inclusivity and diversity; we are united _by_ our differences, not _in
spite_ of them. And, personally, I'm humbled and blessed by the diversity of
animals in my own house right now.`" Bisky could get behind that.

"`So, recap. We're not a cult, and we're not even a personality cult because
there are no personalities to speak of except Balhámoté themself. I'm just
one deer offering information, I'm not a leader, there are countless others
just like me. Our Faith does not promote evil, but instead, other faith
systems are _confused_ about which behaviors are actually evil.`"

Bisky was entranced.

"`Maybe all of you were _way past_ everything I just said, but I think it
bears repeating. Our Faith emphasizes respect for those who deserve it, and
shutting out those who don't. Any questions? Let's have a discussion.`"

Bisky's paw shot up.  "`What is Balhámoté's gender?`"

"`Balhámoté does not have a gender,`" Winter explained. "`Also, their
identity is not defined in terms of male and female, but instead, by the
fact they completely embody balhámotesse, one hundred percent. Or, put
another way, Balhámoté can be described entirely in terms of balhámotesse.`"

"`That's kinda cool,`" said a cat who sat across Bisky.

"`Yes, one of the first things that attracted me to Our Faith is that the
figure we're worshipping isn't some _guy_ telling everyone to stop what
they're doing and instead do _his_ bidding. I'm aware of other faith systems
which have a tendency to alienate women, since the power structures usually
consist of Rather, we are all trying to be more _like_ Balhámoté.`"

Bisky's paw shot up again. "`Can you explain about what you meant when you
said other faiths are confused about what is evil?`"

"`Sure. The point is, I'm aware of faith systems which teach that such
things as drugs, sex, feralism, selfishness, and being gay or transgender,
are _evils_ or impurities and which are contrary to being a good or
spiritually fulfilled animal. But Balhámoté would tell us _none of those
things really matter,_ because if one animal engages with these so-called
vices, they're not actually _harming_ anybody. Balhámoté had a more nuanced
understanding of so-called evils. For example, sex isn't bad, but
non-consensual sex is bad. And being selfish is not bad, but if it's at the
expense of someone else, then it becomes bad.`" 

"`I'm detecting a pattern here,`" said a lioness who sat in the circle.

"`On the flipside,`" Winter continued, "`I'm also aware of faith systems
which seem to condone violence against others for not believing the same
things they do. And then I know of other faith systems which preach zero
violence against anybody. Neither of these are in the vein of balhámotesse.
Again, Balhámoté's understanding is more nuanced. They explain that violence
might be necessary in order to destroy true evils, and animals who are
merely _different_ from you are never evil. Violence is useful against those
who deserve it. But violence is _utterly reprehensible_ when used against
animals who don't.`"

"`I think I get it,`" Bisky said to herself. There weren't any seats per se,
since all of the animals were sitting on the floor, but she felt like she
was at the edge of her seat anyway.

"`In summary, the primary evil is forcing other animals to do things against
their will. All other evils stem from this one. '`Do what you will but harm
none.`' Balhámoté emphasized consent, tolerance and respect for others for
those who deserve it. And doing recreational drugs in reasonable amounts, or
having consensual gay sex is not at all harmful to anyone involved.`"

A badger raised his hand. "`What are the Feral Congregations actually
like?`"

"`That's a good question. Let me explain what they are before I get to your
question, for those who are unaware. So, there's different ceremonies for
different occasions, but the Feral Congregations are the most well known to
outsiders. I think that's because they're so frequent, they happen once a
month, or even more in some areas. And feralism was super important to
Balhámoté. It's more than just _yet another_ "no-evil," like sex and drugs.
Feralism is sacred because, we are animals, and we are _supposed_ to be
feral.  It's who we really are. But feralism is usually banned in
governments and faith systems alike because it's not '`civilized,`' and I'm
sure we've all heard the countless, tragic stories of violence happening at
the paws of animal who had turned feral.`" 

Bisky knew what he was talking about. But she also understood an extra
dimension of feralism that only skunks could comprehend. In Azuaveria, a
skunk using their spray was considered an act of feralism, and subject to
strict penalties, even in self-defense.

"`...But the Feral Congregations turn feralism into an exercise,`" Winter
continued. "`To answer your question: all the animals congregate at one
house, and remain silent, except for two: the owner of the house, and
someone else. The owner of the house leads the ceremonial disrobing by
reciting a few verses from _The Book of Balhámoté,_ and one by one, all of
the animals are disrobed. Eventually, the only animal who hasn't disrobed is
the owner of the house. So, the '`other`' animal recites the verses for the
owner, and then the _next_ Feral Congregation will happen at _their_ house,
and the cycle continues.  It's very fair, and everyone gets a chance to
lead.`"

The animals in the circle leaned in closer to hear. Fortunately for them,
Winter had more to say. "`The specific verses from The Book are designed to
get you into the mood to become feral. Some animals like to take a shot of
dioxylycin as well, to make the experience more transformative, but
personally I rely on the balhámotesse words themselves. The Congregations
are very quiet and meditative, since no one is talking, because I _really_
mean feral. No one is posing, or using feralism as an excuse for bad
behavior.  Basically, the Feral Congregations are an exercise in structured,
voluntary feralism as a form of meditation, in a safe space, and with other
animals.  They're a lot of fun, and you get in touch with your inner animal.
Interacting with other animals in your natural state is really quite
something. That's what they're _really_ like.`"

"`But feralism is illegal in Azuaveria,`" the badger said.

"`Yes, but if everyone does it inside someone's home, and it's consensual,
then it's not _really_ a problem,`" the cat said.

"`Oh, _that's_ where the controversy comes from,`" a wolf noted.

"`I think most animals find the disrobing part controversial in and of
itself,`" the lioness suggested.

"`Maybe Balhámoté would suggest that the Azuaverian law doesn't _deserve_ to
be followed,`" Bisky offered. Winter looked at her for a long time, but she
didn't notice.

The discussion was brewing quite nicely. Winter was speaking less and less,
which was a good sign as far as he was concerned. The animals touched on
several closely related subjects, including spirituality, ethics,
balhámotesse, and more.

Before too long, the informational session came to a close. Winter wanted to
make a few final announcements.

"`Thanks for coming. Feel free to come again to my next informational
session, or even someone else's. I know another follower who likes to do
these things. Or, you know, _don't_, if you believe that studying
balhámotesse isn't for you. There are zero obligations. _But_ if you _are_
interested in joining in the fun and getting your paws wet, then you are
cordially invited to the next Feral Congregation. It will take place next
Friday at 10 PM, right here! I will be hosting. You can bring some friends,
too, but of course I recommend getting them up to speed on some basic
balhámotesse concepts. Oh, and I should mention there's a #balhamotesse
group on YipTalk, feel free to log in and say hi. My nick is simply
'`Winter.`' Farewell!`"

All the animals proceeded to leave, but Winter stopped Bisky.

"`Your comment about Azuaverian law was extremely perceptive,`" Winter
marveled.

Bisky shrugged. "`It seemed logical.`"

"`Well, to me, it indicates you were truly engaging not just with what I was
saying, but what _Balhámoté_ was saying. Have you been doing research on
balhámotesse already? Gone to other meetings? You seemed to pick things up
really quickly.`"

"`No, not really,`" Bisky admitted. "`I mean, I've heard all the
stereotypes.  But I never paid to much attention to them, cuz they're
stereotypes. How about this, it's the first time I've heard it from the
source.`"

The deer nodded. "`Impressive, really. Will I see you at the Feral
Congregation?`"

"`Maybe, I think so,`" Bisky said, although she actually wasn't too sure.

"`Good, good. Well, maybe I'll see you then!`"

"`Right on,`" Bisky said, as she waved goodbye and headed out the door.

The nighttime breeze was cool, refreshing, and clarifying. Bisky _pffft_'d
to herself after thinking about how "`perceptive`" Winter thought she was.

_It's so obvious,_ she thought to herself. _I am a follower of Balhámoté._
