== Chapter 5

Tuesdays and Thursdays were on a different schedule than the other days.
Bisky didn't mind all that much. That's just the way days work, as far as
she was concerned. She still loathed needing to wake up super early, despite
being a morning creature.

_Maybe I'm just lying to myself,_ she pondered, still wrapped up under the
covers. She stared at the bare plaster on the ceiling. _Skunks are supposed
to be night creatures. If I was an actual morning creature, I'd be up and
at'em already. Beating up stupid animals until they keel over. I guess it's
cuz it's not on my own terms. It's on Carmen's terms. The customers want me
there super early, not me. I dunno, I try, don't I? Just trying to make
things better. Other animals suck. Whatever. Okay, here we go._

Bisky climbed out of bed. 6:27 AM. Not too bad, considering.

She took a quick shower, put on clothes and makeup, fluffed her tail,
transferred some leftover taskiak in a plastic container and put it and some
extra chopsticks in her bag. Gardenia knitted the bag for Bisky's birthday
years ago. Occasionally, she did simply stop and admire her friend's
handiwork. It was a simple crafting exercise, featuring an abstract mixture
of different shades of turquoise, but it was also a perfect creation.

The walk to Carmen's was fairly typical, too. Down four flights of stairs,
take a left to head west on Marlsay Avenue, and then right to head north on
the main drag of the Cargo District, Port Boulevard. Bisky always thought
that street name was particularly stupid, since it was situated nowhere near
the actual port. But at least it was a fairly popular Carmen's location,
being in close proximity to some of the touristy draws, such as the block
filled with famous statues. Whenever there was a big event like a parade in
the Cargo District, it would always take place on Port Avenue.

Port Sokuit was a big city with big city problems. The animals who lived
there had to deal with other big city animals. Bisky could always tell a
normal work day from a weekend or a holiday based on the number of animals
around which she had to maneuver in order to get to work on time.  The
entire width of the sidewalk on Port Avenue was frequently packed airtight,
like an unopened deck of cards, and not even on the most busiest of days,
either.

Bisky reminded herself to breathe slowly and deeply, a preventative measure to
guarantee she wouldn't be forced shove the animals out of her way. Or spray
them.

Finally, she arrived at Carmen's. "`Hey, gang,`" she announced as she walked
in. Bisky made sure all the regulars were sitting in their regular places.
So far, there was every indication this was going to be a fairly normal day.
Joyce was able to bellow back with a "`Happy Tuesday, babe,`" since there
was no one in line at the moment.

Joyce noticed Bisky as she walked behind the counter to the employees' area.
"`Your tail looks extra fluffy today. Nice.`"

Secretly, Bisky was beaming. She shook her tail a little. But all she let
out of her mouth was: "`Thanks.`" After a few warm moments to herself, Bisky
continued. "`Yours looks good, too, Joyce.`"

Bisky went into the back room to put away her things. She returned while
tying the brown apron behind her back. "`I had a really weird experience
yesterday,`" she told Joyce while fumbling with the apron. 

"`Yeah?`"

"`Yeah, the woman who owns the building where the family bakery is? She
called me while I was making dinner and scared me.`"

"`Heh,`" Joyce reacted flatly. "`How did she do that?`"

"`She was trying to confirm with me that my uncle, my dad's cousin, will be
in charge of the bakery from now own, but she made it sound like she was
gonna kick us out --`" -- a customer entered, and the little bell on the
door rang -- "`and, well, I totally lost it.`"

"`That blows.`"

"`Yeah, I didn't want my family's whole livelihood to just disappear like
that, you know?`"

Joyce usually spoke in a rough, monotone and seemingly disinterested voice,
but Bisky could tell she meant it when she said: "`I know.`"

Bisky flagged the customer down. He was a snow leopard dressed in very smart
business attire. He carried a briefcase. _Who carries a briefcase?_ Bisky
wondered.

"`Hi, welcome to Carmen's,`" Bisky told the dapper leopard.

"`Hello, -- ... your name is upside-down.`"

"`No, actually, it's Bisky,`" Bisky said. Joyce snorted and headed to the
far espresso machine to clean it up.

"`Your name tag, _sweetie._ It's upside-down.`" Bisky did _not_ like that.

"`Oh! Oops, ha ha ha sorry about that.`" _Are sneps always this cold?_

"`Hello, Hibiscus,`" the leopard said, even though the name tag read
"`Bisky.`" "`I'll have a large light roast.`"

_I'll have a large light roast PLEASE._ "`Do you want room?`"

"`Fill it to the brim, kit.`"

_I'm an adult skunk, you piece of shit fishdick._ "`Coming right up. That's
quite a bit of caffeine, sir. Gonna be a busy day, huh?`"

"`It will be, if you keep this up,`" he said, admiring his own claws at the
expense of everything else in the universe.

Low behind the counter, hidden from view, Bisky patted her lap rapidly seven
or eight times with both paws. "`I guess I'll get started, then.`"

"`Ah-yup.`"

Fortunately, the snow leopard's order was super simple and required zero
concentration. Bisky already expired all of her concentration, having just
spent it on making sure she didn't growl or bite the snep ... or worse.
Bisky was about to put a lid on the cup when he interrupted her. "`I don't
need a lid.`"

"`Alright, here you go. Large light roast.`"

"`I know what I ordered,`" the leopard said as he launched a credit card at
her.

Bisky was about to declare the price of the coffee out of habit, but she
caught herself and decided she didn't want any more berating. And it was
literally her first customer of the day.

Bisky gingerly took the credit card from the leopard's grip. In a dexterous
slight of paw, she was able to read the name embossed onto the credit card
before she swiped it through the card reader and handed it back to him.
Percival Montrusky.

"`Here,`" she said, simply, defeated.

"`Thanks a lot, babe,`" he smirked. He raised his coffee cup as if to
congratulate Bisky for her resounding success. The instant his stupid
spotted tail was fully outside and the door closed behind him, Bisky
launched her head back and flipped her apron over head. Joyce turned to
Bisky when she heard a distant, muffled "`Rrrrrggh!`"

Joyce gently lifted the apron just a hair, to talk with Bisky eye-to-eye.

"`May I come in?`"

Bisky nodded.

"`What a fishdick, am I right?`"

Bisky snorted. "`You're not wrong.`"

Joyce put the apron back to where it belonged. "`Go on, take five. Your tail
is too fluffy for this crap.`"

---

Bisky was able to negotiate working half-days on Tuesdays and Thursdays to
allow herself the ability to attend university at earlier hours on those
days. This arrangement was espeically useful today, to get away from the
toxic environment put in place by you-know-who. She was on campus by noon,
where she found a spot on the main quad by the bell tower and dug into her
taskiak. Leftovers weren't anything like the real deal, but taskiak could be
enjoyed cold, too. There even existed some local skunk-owned businesses who
had recently experimented with making portable varieties that specifically
were cold for easier consumption on-the-go.  Bisky wasn't certain how to
feel about that. Disseminating elements of skunk cuisine and skunk culture
were always welcome, but she just wanted to ensure other animals recognized
that it wasn't _real_ taskiak.

Gardenia would ordinarily join Bisky at lunch on these days, but she was
spending all of her time this week in the music conservatory on the other
side of campus, practicing her violin. Bisky looked at the turquoise,
knitted bag Gardenia had made for her and silently wished her well.
Auditions for the campus orchestra would commence the next week. Bisky
wasn't very musical, let alone artistic, but she knew Gardenia's talent on
the violin was unmatched. Bisky remembered the time Gardenia came over to
her house and presented the famous theme from Julius Marlsay's Symphony No.
2, the theme where Bisky learned that music from a single instrument could
make a skunk surrender and cry. _Really powerful shit,_ Bisky thought.  She
looked around to make sure none of the other animals could hear the sad song
playing in her head. Of course they couldn't. They wouldn't even dare ask
what a skunk is listening to. Skunks didn't listen to music, their smell
just made all the notes turn to musk, and crack from the damage. Bisky
glared imperceptibly at all the other students.

As her eyes scanned the quad, she detected a skunk from the sociology class she
was about to attend.  He sat alone at a nearby table. He was tall, lanky and
awkward-looking, and wore glasses. Bisky figured his entire wardrobe
prioritized simplicity and comfort, given what he was currently wearing. His
tail wasn't fluffy at all, it was... just a tail. He appeared distinterested in
his food, merely swirling it around with his chopsticks. She put her now-empty
container of taskiak back into her bag and approached the skunk.

"`Hey, you're taking sociology with Trousker, right?`"

"`Why, do you need to copy homework from me?`" the skunk said listlessly,
concentrating on the swirling food.

"`Uh, no. I was gonna ask if I could join you,`" Bisky smiled.

Finally, the skunk looked up, and noticed for the first time the cute skunk
girl who sat in the front of the class had approached him on her own
volition.

"`Um, hello, Bisky,`" he said. Bisky didn't notice, but he diverted the
shock way from his face and into his nervous tic of fiddling with his
glasses.

Bisky was taken aback. She was about to ask him how he know her name, but he
filled in her words for her. "`You're wondering how did I know your name.
Everyone knows your name. You sit in the front and don't shut the hell up.`"

Bisky laughed. "`You're not wrong,`" she admitted. "`It's just a super
interesting class, and Trousker is a good professor, too, I think?`"

He shrugged. "`It's a class. Haven't learned anything I didn't already know
yet.`"

Bisky sat down across from him. She noticed he had been swirling some sort
of noodle dish. It looked super yummy.

"`Well, I guess it's easier for skunks to understand concepts like hegemony
and privilege and stuff like that,`" Bisky commented.

"`Yup exactly. Forever on the bottom of the totem pole, as they say. But
that only makes sense if you think about power in that way.`"

"`What do you mean? Also, what's your name?`"

"`Malchus,`" the skunk said. He nervously readjusted his glasses again, then
receded to a more comfortable place.  "`It's a concept I picked up in my
philosophy class. We tend to think about power in terms of '`the many`'
being subjugated by '`the few`'. '`The few`' are on the top of some pyramid,
some small, exclusive upper strata, and '`the many`' are on the bottom of
this pyramid.`"

"`Sounds reasonable...`" Bisky interjected.

"`But it makes sense only in some situations. For example, that structure
might describe wealth distribution very nicely, but it doesn't really
explain the dynamic between, say, canines and skunks.`"

Bisky immediately understood what Malchus meant. "`Yeah, in fact, there are
way more dogs and foxes than there are skunks! At least around here, where
skunks aren't exactly... plentiful.`"

"`Yup exactly,`" Malchus agreed. "`In conclusion, there likely exists a more
nuanced or complex way of describing certain interactions of power than a
pyramid or a totem pole. Concepts like hegemony and privilege are very
interesting and difficult things. Also, Bisky, your eyes have widened so
much that it is beginning to scare me.`"

Bisky squinted and shook her head. "`Oops, sorry, heh. I just find all of
this stuff fascinating.`"

"`Are you a sociology or philosophy major?`" Malchus asked.

"`No, I'm in mar-tech.`"

Malchus because at once visibly perplexed and invisibly turned on. "`That
was unexpected,`" he stated.

The bell tower struck 1 o'clock.

"`Oh, shit, we should get going,`" Bisky said hurriedly.

"`...actually, I'll see you there later,`" Malchus said. Bisky thought that
was a little weird, but didn't have much time to think about it. She smiled
and nodded and then rushed to the building where Professor Trousker led the
small discussion-oriented sociology course.

Trousker's course and classroom could seat a maximum of twenty or thirty
students, in stark contrast to Churaldi's popular mar-tech lectures and the
enormous lecture hall that was required in order to deliver them.

Professor Trousker, a comparatively young badger, had already begun her
class when Bisky flung the door open.

"`Miss Damiat, I'm glad you could make it,`" Trousker said. "`Take your
seat.`"

"`Yes ma'am!`" Bisky complied enthusiastically. She proceeded to her
favorite desk, the one directly in front of her professor, the one where no
one else dared to sit.

The class went almost exactly as Bisky wanted it. She learned a lot, and
despite sitting in the very front, was able to see plenty of students get
uncomfortable over some of the concepts Trousker was introducing. Sociology
filled in all the gaps of Bisky's yearning for knowledge which maritime
technology could not. Sociology _blew her mind_ wide open and shed light and
clarity on her own life.
