== Chapter 2

The only reason Schooner Bailey's wasn't filled to the brim with animals
nearly busting out of its palmwood walls was because it was Sunday
afternoon. For once, the establishment wasn't understaffed, nor did anyone
need to shout in order to be heard even if they were sitting right next to
each other. Bisky and Gardenia were not accustomed to this misleadingly
peaceful setup -- neither of them could remember a time they saw the pub in
daylight -- but, as always, it remained a welcome and familiar spot. And the
food was _amazing_ for a pub in the Cargo District.

The skunks approached the bar. Their favorite bartender, a gregarious but
perpetually overworked cat named Jem, recognized the skunks from afar. Truth
be told, the only skunks who ever came to Schooner Bailey's in the first
place were Bisky and Gardenia. 

"`Welcome, ladies,`" he announced from behind the bar. Gardenia waved in
that annoying but endearing way Jem came to expect. "`Hey, Jem!`" she
responded. Bisky didn't say anything, let alone show any emotion.

Even though the skunks expected it, they were nevertheless a little
perplexed at how _empty_ the place was. Only a few animals sat at a few
tables inside. Their game plan typically involved blending into the
boisterous crowd; now, they could gain privacy if they wanted to just by
sitting in a corner.

"`It's Sunday afternoon,`" he shrugged, when he noticed the skunks were
looking around the place as if it was condemned, or had suddenly became
haunted. "`Actually, I don't think I've ever seen you at this time of day!
Maybe there's time to finally chat?!`" Jem inquired.

Bisky smirked, knowingly.

Gardenia turned to Bisky. When Bisky noticed Gardenia looking, she wiped the
smile off her face clean.  "`...Actually, we need some time to ourselves,`"
Gardenia said as sweetly as she could, still facing Bisky.

"`Cool cool cool,`" said Jem. Secretly, he felt relief, knowing he had less
work to do. "`What can I get ya?`"

"`Frisky Fizz for me,`" Gardenia said.

Bisky consulted the drinks menu, written in chalk on a blackboard behind the
cat.  She quickly located the beer with the highest alcohol content.
"`Seventh Vixen, please. A big one. And a basket of calamari.`"

Jem raised an eyebrow, but punched in the order on the computer anyway.
"`Cool cool cool.`"

"`Yeah, calamari!`" Gardenia accorded.

Jem poured the drinks. Bisky's beer was hilariously larger than Gardenia's
soda pop.  Gardenia paid for it all. The skunks had already agreed to let
this be Gardenia's treat, just this once.

"`Heh, looks like you can have nearly any seat you want,`" Jem said. "`I'll
bring the food out to you when it's ready.`"

The skunks decided to have a seat outside, in the area that was essentially
a garden, but only to the maximum extent that an old, charmingly dingy pub
in the Cargo District could possibly maintain a garden. Some other animals
were already seated on the long benches.

It truly was a beautiful day. Even Bisky noticed. She took a long,
refreshing swig of Seventh Vixen, closed her eyes and leaned back, pressing
her back against the tall, wooden fence. The sun shone on her face. She took
a deep breath through her nose and smiled widely.

"`Feels good,`" Bisky said.

Gardenia took a sip. "`Yeah?`" she asked, over the muffled _fizz_ sound.

"`Yeah.`"

"`What happened back there, anyway?`"

"`Oh, my offering?`"

"`Yeah.`"

Bisky thought about it for a bit. Her eyebrows furrowed as she let her tail
fall to the ground. Gardenia leaned in a little bit. Bisky took a big gulp
before continuing:

"`It was really weird. I, like, _became_ my mother, or something. Pretty
messed up.`" 

"`You did seem... _possessed_,`" Gardenia admitted.

"`Yeah. I guess that's what it was. Somehow my mom's spirit came down and
took over me? I really still don't believe it actually happened. I think
I'll just try to forget about it, I've seriously creeped myself out. I
dunno.`"

"`Maybe it's, like, some sort of calling? Some kind of... did you feel
_chosen?_`" Gardenia ventured. 

"`I felt mostly like a fish out of water, to be honest.`"

Jem arrived with the basket of calamari and a small selection of sauces.
"`Here you are, ladies!`" He put them on the table between the two skunks.
"`Enjoy!`"

"`Thanks, Jem,`" said Gardena.

"`Cool cool cool.`" He awkwardly walked back inside.

As soon as Jem was out of earshot, Bisky leaned in further. "`He totally
digs you, Gardenia.`"

Gardenia snorted. "`He's too cool-cool-cool for me,`" she said
disparagingly. She grabbed a pawful of calamari and shoved it in her mouth.
Bisky just laughed and laughed. Her friend was _never_ that mean.

The other animals, an alligator couple and a trio of foxes, all turned their
heads to face the rambunctious skunk. Gardenia looked visibly uncomfortable,
but Bisky could feel their glares weighing down on her. She combatted this
by taking a big, deliberate swig of her beer while staring each of them
directly in the eye. They heard her gulp the beer as it traveled down her
throat. After a final swallow, Bisky broadcast a purposeful "`Ahhhhh`" to
signify the beer was, in fact, refreshing -- unlike their bitter stares.

"`You're drunk already?`" Gardenia whispered to Bisky.

"`Yeah, well,`" Bisky proclaimed mindlessly. She took a strip of calamari,
dipped it in the spicy sauce, and popped it in her mouth with a crunch. "`My
dad died and I had a creeptastic séance or something at the temple. Cut me
some slack.`"

"`You're right. Sorry.`" Gardenia quietly sipped her Frisky Fizz.

The skunks ate in silence for a minute. The charmingly dingy "`garden`" of
Schooner Bailey's had returned to normal, while the other animals talked
amongst themselves again. Bisky realized it still was actually a beautiful
day, despite her suspicion the other animals were talking about her.

Especially the foxes. They always looked so preppy. They were always the
most popular ones. She knew this all along. It was somehow the natural order
of things. Foxes were charming. Skunks invariably smelled bad. Foxes were
smart and successful. Skunks had to work twice as hard to be recognized for
their achievements. Foxes laughed and it was cute. Skunks laughed and it was
annoying. Bisky glared very, very slightly at the foxes and slowly shook her
head, making sure to not make any sudden or noticeable movements.

"`Well, maybe going back to work and school will help you take your mind off
of those things,`" Garden said. She didn't realize she had interrupted
Bisky's high-speed train of thought. But Bisky didn't make it known to her,
either.

"`Yeah. I'm screwed for school. At least my professors are all
understanding.`"

"`That _is_ nice. Everyone understands what bereavement is. You don't need
to be a skunk to understand what it's like to lose somebody.`"

"`Thank the Maker,`" Bisky said. "`But, I _wasn't_ able to get the day off
for the Mephitidaean Autumn Vigil last year. Professor Warling said the
Vigil takes place at night, and his lecture takes place during the day, so
there wasn't a good enough reason to take the whole day off. My ass. What a
fishbrain. So, that's why I switched my schedule. Café in the morning and
school at night.  Works a lot better for everyone involved, if you ask me.`"

Gardenia wasn't sure what to say. She wasn't able to get that day off,
either.

Bisky finished her beer. She focused on the mug in her paw and played with
it idly. Without looking up, she said simply, "`I think I'm ready to go back
now.`"
