== Chapter 2

The only reason Schooner Bailey's wasn't filled to the brim with animals
nearly busting out of its palmwood walls was because it was Sunday
afternoon. For once, the establishment wasn't understaffed, nor did anyone
need to shout in order to be heard even if they were sitting right next to
each other. Bisky and Gardenia were not accustomed to this misleadingly
peaceful setup -- neither of them could remember a time they saw the pub in
daylight -- but, as always, it remained a welcome and familiar spot. And the
food was _amazing_ for a pub in Port Sokuit's Cargo District.

The skunks approached the bar. Their favorite bartender, a gregarious but
perpetually overworked cat named Jem, recognized the skunks from afar. Truth
be told, the only skunks who ever came to Schooner Bailey's in the first
place were Bisky and Gardenia. 

"`Welcome, ladies,`" he announced from behind the bar. Gardenia waved in
that annoying but endearing way Jem came to expect. "`Hey, Jem!`" she
responded. Bisky didn't say anything, let alone show any emotion.

Even though the skunks expected it, they were nevertheless a little
perplexed at how _empty_ the place was. Only a few animals sat at a few
tables inside. Their game plan typically involved blending into the
boisterous crowd; now, they could gain privacy if they wanted to just by
sitting in a corner.

"`It's Sunday afternoon,`" he shrugged, when he noticed the skunks were
looking around the place as if it was condemned, or had suddenly became
haunted. "`Actually, I don't think I've ever seen you at this time of day!
Maybe there's time to finally chat?!`" Jem inquired.

Bisky smirked, knowingly.

Gardenia turned to Bisky. When Bisky noticed Gardenia looking, she wiped the
smile off her face clean.  "`...Actually, we need some time to ourselves,`"
Gardenia said as sweetly as she could, still facing Bisky.

"`Cool cool cool,`" said Jem. Secretly, he felt relief, knowing he had less
work to do. "`What can I get ya?`"

"`Frisky Fizz for me,`" Gardenia said.

Bisky consulted the drinks menu, written in chalk on a blackboard behind the
cat.  She quickly located the beer with the highest alcohol content.
"`Seventh Vixen, please. A big one. And a basket of calamari.`"

Jem raised an eyebrow, but punched in the order on the computer anyway.
"`Cool cool cool.`"

"`Yeah, calamari!`" Gardenia accorded.

Jem poured the drinks. Bisky's beer was hilariously larger than Gardenia's
soda pop.  Gardenia paid for it all. The skunks had already agreed to let
this be Gardenia's treat, just this once.

"`Heh, looks like you can have nearly any seat you want,`" Jem said. "`I'll
bring the food out to you when it's ready.`"

The skunks decided to have a seat outside, in the area that was essentially
a garden, but only to the maximum extent that an old, charmingly dingy pub
in the Cargo District could possibly maintain a garden. Some other animals
were already seated on the long benches.

It truly was a beautiful day. Even Bisky noticed. She took a long,
refreshing swig of Seventh Vixen, closed her eyes and leaned back, pressing
her back against the tall, wooden fence. The sun shone on her face. She took
a deep breath through her nose and smiled widely.

"`Feels good,`" Bisky said.

Gardenia took a sip. "`Yeah?`" she asked, over the muffled _fizz_ sound.

"`Yeah.`"

"`What happened back there, anyway?`"

"`Oh, my offering?`"

"`Yeah.`"

Bisky thought about it for a bit. Her eyebrows furrowed as she let her tail
fall to the ground. Gardenia leaned in a little bit. Bisky took a big gulp
before continuing:

"`It was really weird. I, like, _became_ my mother, or something. Pretty
messed up.`" 

"`You did seem... _possessed_,`" Gardenia admitted.

"`Yeah. I guess that's what it was. Somehow my mom's spirit came down and
took over me? I really still don't believe it actually happened. I think
I'll just try to forget about it, I've seriously creeped myself out. I
dunno.`"

"`Maybe it's, like, some sort of calling? Some kind of... did you feel
_chosen_?`" Gardenia ventured. 

"`I felt mostly like a fish out of water, to be honest.`"

Jem arrived with the basket of calamari and a small selection of sauces.
"`Here you are, ladies!`" He put them on the table between the two skunks.
"`Enjoy!`"

"`Thanks, Jem,`" said Gardena.

"`Cool cool cool.`" He awkwardly walked back inside.

As soon as Jem was out of earshot, Bisky leaned in further. "`He totally
digs you, Gardenia.`"

Gardenia snorted. "`He's too cool-cool-cool for me,`" she said
disparagingly. She grabbed a pawful of calamari and shoved it in her mouth.
Bisky just laughed.
