== chapter x5 (in which bisky goes to U-Az club day)

Bisky arrived on campus in the early afternoon, like normal, but the scene
was almost totally unrecognizable.  The main quad by the bell tower at U-Az
had been transformed into a veritable marketplace, with hundreds of
representatives from all kinds of on-campus organizations giving pitches to
hundreds of potential members.  Bisky combed the rows and made a mental note
of where the interesting organizations were stationed. She also made sure to
stay away from the clubs that seemed... particularly unwelcome. 

The set of all special interests was truly diverse. Beyond the general
fraternities and sororities (_a club for females because... you're all
female?_), Bisky discovered sports teams, groups focused around specific
arts and crafts, groups about video games, groups which were actually just
study groups (_ha ha ha, no_), groups for specific kinds of animals (_dogs
and foxes just circlejerking?_) and more. In particular, Bisky encountered
three clubs which piqued her interest: The Campus Mephitidaeans, the LGBT
group, and the scale modeling group.

Making models of vehicles was a serious hobby for lots of Azuaverians. It
was an Azuaverian tradition with centuries of history and technical
improvements for ships in particular. Bisky's attention was immediately
captured by a resplendent model of a centuries-old brigantine which the
group's representatives displayed on their table.

"`The rigging is done really really nicely here,`" Bisky said. She addressed
the three animals who were commandeering the table, but she was really
talking directly to the model ship itself.

"`Oh, ahem, well yes, thank you!`" the ram beamed. He seemed to have been
taken off-guard. "`Rigging her up was particularly annoying, with my horns
in the way, et cetera.`"

"`Oh, you made this?`" Bisky asked.

"`Yes!`"

"`This is really, really, good," Bisky said earnestly.

"`Yeah, she's really beautiful,`" commented the ferret who sat next to him.

"`How did you get the headsails to look like that?`" Bisky wondered. "`It
looks like the wind is blowing into them? Mine just... lay flat, or look
limp and lifeless, you know what I mean?`" 

The ram had a difficult time believing what he was seeing. A girl into ship
modeling? Not just a girl -- a _skunk girl_ into ship modeling?!

"`Er, it's pretty simple if you're using the right material...`" the ram
begun to explain.

-- (stuff)

"`We think you'd fit in very nicely,`" the ferret said.
