== Chapter x2 (in which Bisky confronts the café dogs)

"`I'm gonna take my five,`" Joyce stated. "`Bisky, why don't you clean the
espresso machine?`"

"`Yes, ma'am!`" Bisky announced.

Joyce walked to the back room while Bisky procured a small washcloth from
under the counter. As she wiped the machine, she could see the two dogs whom
Joyce had served coffee. They where sitting in the two fancy armchairs in
the corner. She always was interested in what dogs had to say, even if it
was none of her business. But, at this stage, Bisky's business had
transformed into something else entirely. She may as well have changed
careers.

"`Skunk's kinda cute.`"

"`Yeah. Of course she's a skunk, though.`"

"`What do you mean?`"

"`Skunk. Working in a café. Don't you get it? The smell of coffee totally
hides their actual smell. You haven't noticed how skunks are always working
at cafés?`"

"`Heh, hadn't thought of that...`"

"`Works well for everyone involved, I think.`"

"`Really?`"

Bisky scowled in their direction. Without unlocking her gaze, she rapidly
and forcefully patted her lap with both paws. Her grip tightened on the
washcloth and water rung out.  After ten or fifteen pats, she shot the
washcloth onto the floor and stomped towards the dogs They were talking
about something. She didn't care.

"`Ugh, look, here she comes,`" the husky said.

"`Hai!! I'm your friendly neighborhood barista. Did you know that I don't
actually smell bad? Maybe I'm making coffee in the morning for unenlightened
beasts such as you two fine specimens because _I'm a poor college student_
and for no other reason?! Did it occur to you that not everything that I do
has to do with masking my musk? Did you know that dogs also commonly work as
baristas, but you just notice skunks more because we look different??`"

"`It really doesn't sound any fancier when you call it '`musk,`'`" the husky
retorted.  The coyote, on the other paw, seemed crestfallen. Bisky noticed
this, and changed her tone.

"`Hey, champ,`" Bisky told the coyote, "`would you like to do me a favor?`"

"`Uh?`" was all the coyote could manage.

"`Tell your '`friend`' he's a speciesist fishdick.`"

The coyote would have thrust his tail between his own legs if it weren't for
the big chair he was sitting in. The husky's ears drooped and he swapped out
his old face for a new, shiny and utterly horrified one.

"`You heard me. Tell the husky he's said things that are speciesist and
fishdickish, and that it made you uncomfortable.`"

"`_You're_ making me feel uncomfortable,`" the coyote whimpered.

Bisky took a deep breath and squatted to meet the coyote at his level. The
husky instinctually assumed she was getting to spray them, or something
silly like that, but he let his guard down when he realized what she was
really doing. Bisky looked at the coyote in the eye. The coyote was also
afraid at first, but then he saw that her eyes were amethyst in color, and
actually kind of beautiful.

"`You'll feel better if you do it,`" she told him. "`Trust me. Don't do it
for me, even. Do it for you.`"

The coyote needed just a little bit more shoving.

"`It'll feel like... how to put it... like a good, honest _aroo_.
Seriously.`"

The coyote turned to the husky, and spoke deliberately: "`You're a
speciesist fishdick.`" Bisky squealed with joy. The coyote's sigh of relief
resonated across the whole café. The husky was just plain stupefied.

"`See? Not so bad, right?`" Bisky said as she stood up.

The coyote blinked intentionally, as if waking from a dream. 

"`...is that how you really feel?`" the husky asked, obviously hurt.

The coyote sighed again. "`Kinda, yeah.`"

"`I have to go think,`" the husky snarled. He downed the remainder of his
coffee, which he had only barely gotten started with, slammed the cup on the
little table between the two armchairs and stormed out of the place, heading
south.

The coyote panicked for a second. He desperately looked Bisky, and then
looked out the door, then back at Bisky again.

"`I should make sure he's okay... I don't think he's ever been struck down
by a skunk like this before.`"

"`Do the right thing,`" Bisky encouraged.

After a moment of hesitation, the coyote stood up and walked out the door.
He looked to the south, _arooooouuuu_'d proudly and loudly like it was no
one's business, and then headed north and walked away.

Joyce heard the dog's call as she emerged from the back room. "`What's his
problem?`" she wondered.

"`He doesn't have a problem,`" Bisky replied.
