== Chapter 5

Tuesdays and Thursdays were on a different schedule than the other days.
Bisky didn't mind all that much. That's just the way days work, as far as
she was concerned. She still loathed needing to wake up super early, despite
being a morning creature.

_Maybe I'm just lying to myself,_ she pondered, still wrapped up under the
covers. She stared at the bare plaster on the ceiling. _Skunks are supposed
to be night creatures. If I was an actual morning creature, I'd be up and
at'em already. Beating up stupid animals until they keel over. I guess it's
cuz it's not on my own terms. It's on Carmen's terms. The customers want me
there super early, not me. I dunno, I try, don't I? Just trying to make
things better. Other animals suck. Whatever. Okay, here we go._

Bisky climbed out of bed. 6:27 AM. Not too bad, considering.

She took a quick shower, put on clothes and makeup, fluffed her tail,
transferred some leftover taskiak in a plastic container and put it and some
extra chopsticks in her bag. Gardenia knitted the bag for Bisky's birthday
years ago. Occasionally, she did simply stop and admire her friend's
handiwork. It was a simple crafting exercise, featuring an abstract mixture
of different shades of turquoise, but it was also a perfect creation.

The walk to Carmen's was fairly typical, too. Down four flights of stairs,
take a left to head west on Marlsay Avenue, and then right to head north on
the main drag of the Cargo District, Port Boulevard. Bisky always thought
that street name was particularly stupid, since it was situated nowhere near
the actual port. But at least it was a fairly popular Carmen's location,
being in close proximity to some of the touristy draws, such as the block
filled with famous statues. Whenever there was a big event like a parade in
the Cargo District, it would always take place on Port Avenue.

Port Sokuit was a big city with big city problems. The animals who lived
there had to deal with other big city animals. Bisky could always tell a
normal work day from a weekend or a holiday based on the number of animals
around which she had to maneuver in order to get to work on time.  The
entire width of the sidewalk on Port Avenue was frequently packed airtight,
like an unopened deck of cards, and not even on the most busiest of days,
either.

Bisky reminded herself to breathe slowly and deeply, a preventative measure to
guarantee she wouldn't be forced shove the animals out of her way. Or spray
them.

Finally, she arrived at Carmen's. "`Hey, gang,`" she announced as she walked
in. Bisky made sure all the regulars were sitting in their regular places.
So far, there was every indication this was going to be a fairly normal day.
Joyce was able to bellow back with a "`Happy Tuesday, babe,`" since there
was no one in line at the moment.

Joyce noticed Bisky as she walked behind the counter to the employees' area.
"`Your tail looks extra fluffy today. Nice.`"

Secretly, Bisky was beaming. She shook her tail a little. But all she let
out of her mouth was: "`Thanks.`" After a few warm moments to herself, Bisky
continued. "`Yours looks good, too, Joyce.`"

Bisky went into the back room to put away her things. She returned while
tying the brown apron behind her back. "`I had a really weird experience
yesterday,`" she told Joyce while fumbling with the apron. 

"`Yeah?`"

"`Yeah, the woman who owns the building where the family bakery is? She
called me while I was making dinner and scared me.`"

"`Heh,`" Joyce reacted flatly. "`How did she do that?`"

"`She was trying to confirm with me that my uncle, my dad's cousin, will be
in charge of the bakery from now own, but she made it sound like she was
gonna kick us out --`" -- a customer entered, and the little bell on the
door rang -- "`and, well, I totally lost it.`"

"`That blows.`"

"`Yeah, I didn't want my family's whole livelihood to just disappear like
that, you know?`"

Joyce usually spoke in a rough, monotone and seemingly disinterested voice,
but Bisky could tell she meant it when she said: "`I know.`"

Bisky flagged the customer down. He was a snow leopard dressed in very smart
business attire. He carried a briefcase. _Who carries a briefcase?_ Bisky
wondered.

"`Hi, welcome to Carmen's,`" Bisky told the dapper leopard.

"`Hello, -- ... your name is upside-down.`"

"`No, actually, it's Bisky,`" Bisky said. Joyce snorted and headed to the
far espresso machine to clean it up.

"`Your name tag, _sweetie._ It's upside-down.`" Bisky did _not_ like that.

"`Oh! Oops, ha ha ha sorry about that.`" _Are sneps always this cold?_

"`Hello, Hibiscus,`" the leopard said, even though the name tag read
"`Bisky.`" "`I'll have a large light roast.`"

_I'll have a large light roast PLEASE_. "`Do you want room?`"

"`Fill it to the brim, kit.`"

_I'm an adult skunk, you piece of shit fishdick._ "`Coming right up. That's
quite a bit of caffeine, sir. Gonna be a busy day, huh?`"

"`It will be, if you keep this up,`" he said, admiring his own claws.

Low behind the counter, hidden from view, Bisky patted her lap rapidly seven
or eight times. "`I guess I'll get started, then.`"

"`Ah-yup.`"

Fortunately, the snow leopard's order was super simple and required zero
concentration. Bisky already expired all of her concentration, having just
spent it on making sure she didn't growl or bite the snep.  Bisky was about
to put a lid on the cup when he interrupted her. "`I don't need a lid.`"

"`Alright, here you go. Large light roast.`"

"`I know what I ordered,`" the leopard said as he thrust a credit card at
her.

Bisky was about to declare the price of the coffee out of habit, but she
caught herself and decided she didn't want any more berating. And it was
literally her first customer of the day.

Bisky gingerly took the credit card from the leopard's grip. In a dexterous
slight of paw, she was able to read the name embossed onto the credit card
before she swiped it through the card reader and handed it back to him.
Percival Montrusky.

"`Here,`" she said, simply, defeated.

"`Thanks a lot, babe,`" he smirked. He raised his coffee cup as if to
congratulate Bisky for her resounding success. The instant his stupid
spotted tail was fully outside and the door closed behind him, Bisky tilted
her head back and flipped her apron over head. Joyce turned to Bisky when
she heard a distant, muffled "`Rrrrrggh!`"

Joyce gently lifted the apron just a hair, to talk with Bisky eye-to-eye.

"`May I come in?`"

Bisky nodded imperceptibly.

"`What a fishdick, am I right?`"

Bisky snorted.

Joyce put the apron back to where it belonged. "`Go along, take five. Your
tail is too fluffy for this crap.`"
