== Chapter x4 (in which bisky and timo go on a date)

Ordinarily, Bisky would have virtually no business at all in downtown Port
Sokuit, but this day was completely different. She would get to spend a
_whole day_ with Timo the fox.

Bisky, still in her pajamas, confronted her own closet. She opened it to
find what she usually found -- too many dresses that were too small,
underwear that had slightly ripped but for some reason hadn't been replaced
yet (common for animals with large tails), bras that had been stretched out
too much, t-shirts that desperately needed to be washed.

"`Wow, this situation sucks,`" Bisky said out loud.

She let her wardrobe air out a bit for no particular reason while she made
herself some breakfast. Cold-smoked mackerel and a slice of tomato on
toasted sporzo, with a croissant from the family bakery, to be washed down
with orange juice with a lot of pulp.  The only missing ingredient was
capers.  It was the fanciest breakfast Bisky had concocted in months, but
she was desperate to feel fancy in preparation for Timo and the museum. She
sat on her tiny "`apartment-sized`" table and tried to enjoy the meal
instead of simply eating it. She let the sun shine on her face as she leaned
back, closed her eyes, and slowly took a bite.  It was actually kind of
delicious. One of the lessons from her Mephitidaean upbringing which struck
a particularly harmonious chord was that there is beauty in _everything_ if
you look hard enough, and that it was a skunk's mission to locate it. The
more elusive the beauty, the greater the reward for having found it.  Bisky
discovered it was easier to excavate that beauty when she slowed down and
meditated. Bisky also realized the commandment was first postulated in a
time and place where skunks simply didn't interact with other species, but
she tried to ignore that for this moment. She already found enough of a
spark in Timo, and Timo had found one in her, and, well, ... she just didn't
want to screw this up.

After putting the dishes away and taking a shower, she confronted her
wardrobe again with a renewed energy. It looked different. In particular,
the dresses somehow got bigger, and the situation didn't suck anymore.

Bisky selected the dress with the most interesting backstory, took it off
the rack and inspected it. She smiled as she put it on and thought about the
story.

In the bathroom, Bisky spent some extra time putting on her makeup -- a
feeble but acceptable attempt at contouring for a full-beat face -- put on
dangly seashell earrings and fluffed her tail.

Soon, it was time to go. Bisky took one last quick look at herself in the
mirror before heading downstairs. Looked alright. The light rail station was
on the way to work, but she never took it to work because traveling only one
stop wasn't financially worth it.  She lived five our six stops away from
today's destination, the Civic Center, the true downtown of Port Sokuit.
Even on Saturdays, it was bustling with animals and activity and street
music protests and art and culture. Bisky was always astounded and inspired
by the diversity, unlike some other people in her life.

The Port Sokuit Museum of Modern Art was a few blocks away from the Civic
Center. In the distance, she could Timo sitting on the steps to the museum,
already waiting for her. After a minute of navigating the crowds and
crosswalks, she and Timo finally found each other.

"`Hey hey, Bisky!`" Timo said enthusiastically. He seemed genuinely excited
to learn how today would go.

"`Hiya,`" Bisky replied.

A beat of awkward silence stood in their way. Timo leaned in halfway for a
hug, paused, and then fell through. Bisky... was not expecting that. But it
felt nice. It was a very quick but amicable and honest hug.

_I guess you hug customers while not at work?_ Bisky wondered.

"`This is pretty wild, am I right? Getting to see you outside of a café...
to be honest, I thought you were going to show up in your Carmen's uniform!
Because I literally have seen you wear nothing else, hahaha.`"

"`Heh, yeah, no, I wear dresses and stuff when I get the chance,`" Bisky
said.

"`Shall we?`" the fox gestured upstairs, towards the museum's entrance.

"`Yes, of course,`" Bisky said.

"`The thing I like about good museums,`" Timo said as they climbed up the
steps, "`is that you can look at stuff in whatever order you like. You're
not penalized for experiencing things in the suboptimal route. You know what
I mean?`"

"`Yeah, like, you feel the pressure to ride _all the rides_ at Resanna
Realm, and there are lots of animals who have that boiled down to a
science...  that's not fun, really, that's just a test of whether you
remembered what the correct order of roller coasters is. I kinda just like
my taking my time and soaking it all in...`"

Timo was outwardly impressed. "`Right, yeah, exactly! Let's just soak it all
in.`" Meanwhile, Bisky was inwardly impressed at Timo's careful listening.

At the entrance of the museum, patrons had the option of going left or going
right. The sign which offered them that choice was a work of art in and of
itself -- it was a grand mural which featured a vast collection of animals
and other objects leaning, pointing or otherwise indicating the left on its
left side, and a similar arrangement on the right side. The objects ranged
from household items and street signs to plants and other natural phenomena.
The animals were as diverse as Port Sokuit.

"`Left or right?`" Timo asked.

Bisky studied the mural itself. It wasn't at all symmetrical from a
geometric perspective, yet it looked balanced. The sets of objects and
animals on both sides were fairly disjoint. But Bisky did not have the
vocabulary to explain what she was seeing. Gardenia was the artistic one.
Bisky was the engineer. But she was compelled to say something that sounded
at least vaguely intelligent. That's what you're supposed to do at museums,
right?

"`It's like... balanced, but it's not? This thing?`" _At least I tried?_

Timo studied the mural itself. "`Ah, yeah, I see what you mean! It's not at
all symmetrical from a geometric perspective. But it does looked balanced.
It's remarkable, in my opinion, how the artist was able to maintain the
balance, despite the sets of objects and animals on both sides being fairly
disjoint. Fascinating.`" 

Now Bisky was scared.

"`Uh, let's go left!`" she decided.

"`Awesome,`" the fox said. They turned left.

Bisky was not used to feeling scared. Not of a _fox._

The fox and the skunk turned another corner and found themselves in a large
hall. The hardwood floors and wide, empty spaces allowed the voices of
animals and the clomping of shoes and paws to reverberate freely. Paintings
were hung on the walls and some few statues were situated between them, in
the middle of the hall.

"`Oooh, look at this,`" Timo said excitedly but quietly. The work he was
referring to was painted on an enormous portrait-oriented canvas, perhaps
twenty hands tall; he did not need to walk too much further in order to
enjoy it properly.

"`Okay, yeah, that's pretty cool,`" Bisky said, awestruck.

The painting was at its essence a full-body portrait of a female zebra,
walking slowly towards the viewer, but the zebra's stripes were composed of
ribbons strewn about in the form of a zebra. Most of the ribbons were black
and white, naturally, but there was also the occasional magenta ribbon, and
those stood out easily on their own. The portrait inspired Bisky, which was
another feeling she was not accustomed to.

"`It's interesting how the artist decided to make a painting of the ribbons,
rather than attempting to create the thing with actual ribbons,`" Timo
remarked.

"`It's probably not physically possible, and if it were, it'd be a bitch to
keep in the right shape,`" pragmatic Bisky offered.

"`I'm mostly intrigued by how it's partially a painting and partially a
sculpture. But not in the mixed-media sense of a painting-as-a-sculpture.
This zebra _could_ have been built, but instead that _built_ thing is
captured here as a painting. It's interesting!`" Timo was all over this.

"`...Yeah!`" was all Bisky could say out loud. Internally, though, she
wanted to tell him that the strength of her crush could pulverize an entire
ship.

The Port Sokuit MoMA was a very large, expansive space, and patrons
typically did not take a tour of the entire collection in one day, if they
were to take their time and soak it all in as Bisky and Timo were. Bisky
wished she could comprehend the greatness of the works she  was looking at.
If these artists were at all renowned, she would not know. Another one of
those "`Gardenia to the rescue`" situations. Hardly any of them had skunkish
names, that was for sure. Bisky convinced herself that problem could be
easily solved by letting one of Gardenia's paintings hang on the MoMA's
walls.

An entire hour or two of museum-going had passed, and Bisky still felt
apprehensive about talking about art with Timo. She was afraid that Timo
would get bored of her obviously novice understanding of what she was
looking at. She was afraid that her appreciation of the art was too
superficial for Timo's tastes. She was also afraid that someone would try to
get her ejected from the museum for being a skunk.  Bisky kept searching for
signs that these would be the case, any hints or indications, but she found
none whatsoever.  As far as Bisky could tell, Timo appeared to be genuinely
interested in what she had to say about all the artwork, even though it
seemed to her he had to _stoop down_ to her level.

Eventually, both of them were starting to get hungry, and decided getting
themselves a late lunch would be prudent. In order to leave the museum, they
needed to go back the way they came.

"`I'm glad I made the decision to go left,`" Bisky told the fox.

"`I'm glad, too!`" he concurred.
