== Chapter 0x

This time, Bisky and Gardenia weren't at all confused as to whether they
were in the right place. Schooner Bailey's was absolutely packed with
animals. You couldn't tell by looking, since they liked to keep the lights
fairly dim inside, even at night, but any beast within seemingly a league of
the place could hear all of the excited commotion within.

Bisky and Gardenia could see the establishment's famous palmwood doors on
from the opposite corner. Bisky pushed the pedestrian crosswalk button and
waited for their turn. "`Hey Gardenia,`" said Bisky, "`How much you wanna
bet that the industrious Jem will be working tonight?`"

"`A hundred bucks,`" Gardenia replied without hesitation. "`He's, like,
_always_ there. I like him alright, but, meh, I dunno.`"

"`He just thinks you're really cute or something. I mean, you _are_ super
nice.`"

"`Cute is not the same thing nice.`"

The signal changed and the skunks crossed the first street. 

"`Fair nuff... but, are you saying you aren't _nice_, Gardenia?`"

Gardenia shrugged. "`I just... I just don't want to think too hard about
anything right now,`" she admitted. "`I've been stressing out.`"

Bisky hit the next crosswalk button and waited to cross the other street.
"`You'll do fine! Seriously, you're _so good_ at the violin.`"

"`Maybe I am, until it's just me and the conductor and the artistic
directory in a small room and nobody else. I don't know if you know, but
that's _frightening._`"

"`That's only two animals,`" Bisky said. "`It's easier to be comfortable
with smaller groups, I find.`"

"`Yes, but they're not my friends. It's their _job_ to _judge_ me. Friends
aren't like that,`" Gardenia retorted.

"`...you're not wrong,`" Bisky said.

The crosswalk signal changed and the skunks proceeded to the pub.  When they
entered, they were shocked to discover two things: how much louder and
boisterous than normal it was inside, and also a bouncer sitting behind a
small podium positioned squally next to the door. He was a large,
impenetrable and just plain scary-looking grizzly bear with whom Gardenia
did _not_ want to fuck with, and with whom a drunk Bisky might have gotten
into a confrontation.

Gardenia immediately began to sift through her purse to find her ID, but
Bisky's first inclination was to ask the bear: "`Since when did Schooner
Bailey's start bouncing animals?`"

"`New policy,`" he stated in an impossibly low voice. "`Too many kids using
fake IDs.`"

Gardenia handed him her ID. It was hilariously small compared to the
grizzly's giant paw.

"`That's funny. Why would they do that?`" Bisky wondered out loud. "`They
should've known all the staff behind the counter are super nice and would
just give drinks to anyone who deserved them...`"

The grizzly bear graciously thanked Gardenia and returned her ID.

"`Also, don't you feel like it's something that bartenders should be able to
figure out on their own? A fake ID from a real one?`"

"`ID, please,`" the bouncer said.

Bisky noticed Jem was actually working. He was rushed and looked stressed,
as always. "`Look, see, Jem's working. He's checked my ID before, it's
fine.`"

"`I need to check your ID,`" the bouncer insisted.

Gardenia was clearly annoyed. "`Come on, Bisky, just show him your ID.`"

But Bisky kept going. "`We're _regulars,_ my grizzly fella. Gardenia and I
come here all the time. It's no big deal!`"

The bear leaned over his tiny podium and stared directly into Bisky's soul.
Gardenia was terrified.  All of the music and chatter in the pub muted for
Bisky. "`Listen carefully,`" the bear said deliberately. Bisky listened
carefully. "`When I kick animals out, I kick them so hard, they _fly_. And
you, since you're so special, I'll tell your precious Jem about how I licked
you clear to the other side of town and how you lost your right to _step paw
inside of this establishment ever again._ Do you have your ID with you, yes
or no?`"

"`Actually, it's a privilege, not a right,`" Bisky said.

Incredulous Gardenia asked herself: "`What?`"

"`Get out of here _now_, skunk,`" the bear threatened. And he truly was
threatening.

"`Ugh, fine, here,`" Bisky relented. She fished around her bag for her ID
and showed it to him. He snatched it from her paw and scrutinized it extra
carefully. After a short lifetime, he returned the ID to Bisky.

"`Enjoy your _stay_, skunk,`" the grizzly bear concluded.

Gardenia and Bisky carefully maneuvered around the maze of customers,
waiters, tables and chairs, vaguely in the direction of Jem.

"`What the hell was that?`" Gardenia snapped.

"`I shouldn't _need_ to show him my ID, I'm not part of the problem!`" 

"`What?!`"

"`The problem was stupid kids using fake IDs. I had nothing to do with
that.`"

"`Not sure how else to say this, Bisky, but the bouncer doesn't know nor
does he care who you are.`"

"`He doesn't need to _care_ about me. It's just unfair that everyone, even
the well-liked regulars, --`"

"`Get a grip, Bisky,`" Gardenia interrupted. `"We almost got kicked out of
this place _forever_ because of your stupid stunt.`"
