== Chapter x15 (in which bisky visits the MILF) 

(XXX she's at the campus mephitidaeans, but towards the conclusion of the
meeting:)

"`If you want to stop just hanging around here and see some _real_ action,
stick around after everyone else has left,`" Malchus announced. Bisky was
intrigued.

"`Well, actually, that's all I have,`" Daisy admitted. "`Hope to see you all
next week!`"

Approximately half of the skunks actually left, including Daisy. The other
half, which included Bisky, stuck around and eagerly awaited for Malchus's
explanation. What was "`real action?`"

One of the other male skunks folded open a plastic table. Malchus drew from
his backpack a prominent flag of black, white and red horizontal stripes.
The center consisted of a stripe of white sandwiched by two black stripes,
which was a fairly universal symbol of Mephitidaeans, or skunks in general.
But sandwiching _that_ were two stripes of red, which Bisky had to admit was
not typical and rather...  confrontational. Malchus hung the flag from the
table for all of the other skunks to see, then he and the other skunk stood
on top of the table. It was weird and offputting to see skunks elevated
above other skunks, and talking down to them.

The room seemingly transformed from a simple, modest religious gathering
into something completely different. Bisky imagined banners unfurling from
the cieling, carpets unrolling themselves, and day suddenly gear-shifted
into night. And most shockingly, the quiet, awkward and meek Malchus
magically leveled up and seemed to assume an entirely new identity.

"`The truth of the matter is,`" Malchus declared with a conviction that
Bisky did not think possible of someone like him, "`going to the temple and
praying and doing the same thing we've been doing for thousands of years
_just isn't gonna cut it anymore._ It certainly makes us better animals,
being the One True Faith and all, but the blunt, brutal truth is that skunks
are _oppressed_ and we have been this whole time and we've been _idling_ in
our little corner for way too long. Skunks hang around each other all the
time not because we _want_ to, but rather _in spite._
