== Chapter x12 (in which bisky and timo agree to go on a date)

_Some animals are just plain gross. They don't even care. They totally
forget that this space isn't just for them. But how could anybeast forget
that? And even if you did think this space was only for them, why would you
leave it so messy for yourself? It doesn't make any sense. Who can possibly
tolerate this? Have some dignity for yourself, even. Feral beasts, all of
them..._

Bisky ran all of these thoughts through herself as she dipped the mop into
the bucket and dragged it across the bathroom floor for what felt like the
hundredth time today. She looked up and saw all sorts of paw prints on the
wall near the toilet and the sink. _What are animals even doing in here?_
She considered mopping the walls, that's how gross Carmen's bathroom was
today.

Joyce's monotone voice reverberated brightly off of the walls, as nasty as
Bisky thought they were. "`Bisky, what's up, babe? You're taking forever in
there.`"

Bisky snorted. "`It was really gross in here. Do we need to get a bigger
trash can or something? Animals keep _missing_ it.`"

Joyce shrugged. "`Dunno. Some animals are just plain gross.`"

She raised an eyebrow when she saw Bisky smile and laugh.

"`You think that's funny?`"

"`Naw, Joyce, it's just, you took the words straight from my brain.`"

"`Heh. Actually, it's an intercranial device. I can hear the thoughts of
other animals who are on the same frequency as me.`"

Bisky snorted, her smile widened. Joyce, on the other paw, never smiled, and
her idiosyncratic variety of "`laughing`" had the capacity to make other
animals shift uncomfortably in their seats, but Bisky knew she was just
playing "`lightheartedly.`"

The bell on the door jingled, signaling the arrival of a new customer.

"`Seriously, babe. Wrap this up.`"

"`Aye aye!`"

Joyce looked over her shoulder and reacted audibly. Bisky understood that
meant she _really_ should get a move on, in order to see what her boss was
seeing.

And she was glad she did.

Right on schedule, Timo stood in line on early Thursday afternoon and was
contemplating the menu. He always ordered something different every time.
Bisky appreciated that it certainly kept things interesting, but there were
more important things going on. Timo was the fox with the gentle soul and
beacon of joy in Bisky's Thursday. Timo was the fox who reinvigorated
Bisky's belief in other animals. Timo was the fox who wore his heart in his
mind and his mind in his heart.

And it drove her insane, nearly to the point of losing control of her own
scent glands, that he was in fact a fox.

Bisky skipped to the register and waved like Gardenia did. She did not
notice the smirk sculpted on Joyce's face.

"`Hey hey, Bisky!`"

Bisky could only speak in smiles.

"`I'm truly glad to see you,`" Timo said earnestly. "`Hey,`" he said to
Joyce.

"`Hey,`" Joyce replied.

Timo returned his attention to the skunk. "`Feeling better?`"

Bisky nodded. "`Yes, thank you, Timo.`"

"`I've missed you,`" Timo said. "`Um, do you need to get back to cleaning?`"

"`No, I finished,`" Bisky said gently for some reason.

"`So that mop is just a fashion statement,`" Timo joked.

Bisky cranked her head slowly to the left to discover she was still in fact
holding the sopping mop. Her smile blossomed ever more sheepish, which was
impressive, considering she was not at all a sheep.

"`Ah, yup,`" Bisky broadcast through her stupid grin. "`This is an haute
couture walking mop.`"

Timo never laughed at others. He only laughed with them. "`Artisinally woven
mopping silk attached to the only the finest beechwood handle.`"

"`Yeah, canes are so last year, ha ha ha ha ha.`"

After Bisky decided she was drawing this moment out too long, she asked Timo
to wait just a second for her to put it back in the closet. He took that
opportunity to finalize his order.

Bisky returned to the register and laughed some residual laughs.
"`Seriously, dude, I'm alright. I feel a lot better. I think I can make it
through this.`"

"`That's excellent.`"

"`What can I get ya?`"

"`I want to get in the autumn mood... how about a pumpkin spice latte?`"

Bisky selfishly wanted him to order something more... adventurous. That was
probably the most boring thing he had ever ordered ever since he learned how
to say "`Carmen's.`"

Bisky instinctively grabbed a large mug. She confirmed: "`Large, for here?`"
at the same time Timo was telling her that.  They giggled simultaneously,
too. Joyce just rolled her eyes.

Timo took a seat at a table for two. Only rarely did anyone accompany him.
Bisky noticed his aloneness as she brewed the coffee. She poured the coffee
and the soymilk into the "`for-here`" mug delicately and artistically, in a
seeming attempt to make a foam heart. Joyce noticed this from the corner of
her eye, and became immediately suspicious, because Bisky never attempted to
do that before. Joyce was also suspicious because Bisky was, to put it
lightly, not very artistic. But Bisky was humming and beaming with joy, the
happiest she had ever seen her in weeks, so she let her have her moment.

At this point, she would ordinarily call the customer's name to inform them
their order was ready, but instead, Bisky carried the mug all the way to
Timo.

"`Here you go.`"

"`Wow, thank you,`" Timo said truthfully. He looked at the pitiful excuse
for foam art which gated his entrance to the sweet pumpkin spice. He admired
how imperfect it was, how it looked more like a pancreas than a heart.  He
closed his eyes and took a slow, methodical sip. "`This is really good,`" he
remarked.  Bisky was pleased.

"`Do you have a minute?`" Bisky asked.

"`Sure, sure!`" Timo thought she'd never ask.

Bisky took the seat next to him. It was the annoying small chair that Bisky
hated sitting in, since her tail was nearly as big as it, but that hardly
mattered in this instance.

"`I'm actually really glad to see you,`" she said with reverence.

"`Same!`" Timo yelled cheerfully. Sometimes, Bisky wondered if he was
partially deaf."`Hey, I wanted to ask you last week, but you were away:
there's a bunch of new exhibits at the MoMA, do you wanna come along?`"

Bisky did _not_ see that one coming, like a magic trick.

"`Wow, uh, the museum?`" she asked. She asked partially because she didn't
know what else to say, and partially because she actually wasn't certain
whether the "`MoMA`" was actually the Port Sokuit Museum of Modern Art.

"`Yeah, yeah!`" Timo confirmed, swallowing another gulp of pumpkin spice.
"`It'll be fun. What do you think?`"

Bisky was clueless about art, but it would be definitely be _quite
interesting indeed_ to interact with Timo outside of work.

She had great difficultly reining in her excitement. "`Sure, let's do it,`"
she said as coolly as possible, that is, as cool as a muffin pan just out of
the oven. "`I'm not doing anything Saturday...`"

"`Saturday it is, then,`" Timo finalized. Bisky still didn't quite believe
what had just happened. She proceeded to engage in a daydream of spending
_all day_ with Timo the fox... but it would only be a fleeting one, and
scurried back into its hole when the door jingled.

She indicated the new customers to Timo, and he nodded in understanding as
he took another sip from his mug.  Bisky got up, dusted off her apron,
skipped quickly over to her station, and then it was business as usual.

Before too long, Timo had to go. He refused to interrupt Bisky and her work
any further, but she was in the middle of taking care of an order. So, on
his way out, he gave Joyce a napkin decorated with some numbers from a pen,
and asked her to pass it on to Bisky.

Despite now having his number, an unfamiliar mixture of melancholy and hope
subsumed Bisky when she noticed the fox leaving. She wanted to tell him all
about it. He would listen. She sighed wistfully as she prepared another cup
of coffee for someone who was not Timo.
