== Chapter x10 (in which bisky sails alone)

Bisky did not usually have mornings to herself, but she was going to make
the most out of this one. She prepared a simple breakfast: an almond muffin
from the family bakery, warmed up, sliced, and lightly dressed with honey
flavored with anise, with sliced mackerel on the side and a glass of lime
juice.

After quietly enjoying her meal, she proceeded to the bathroom, carrying her
chair with her. She confronted the shower curtain and stood her ground. It
showcased a simple design, featuring a single, large, stylized starfish atop
a field of white.  Bisky put the chair close to the shower and she stood on
it. And while on her pedestal, she closed her eyes, took a deep breath and
spoke as quietly she could: "`I'm so sorry, dad.`" 

Bisky squeezed her eyes tight and thrust her arm through the rod of the
shower curtain. It fell into the bathtub with a hard and unusually loud,
metallic _clank_. She hopped off the chair unplugged the rubber stop off of
one end of the rod. It contained several thinner rods, a far heavier and
sturdier one, for it was the reason behind that _clank_. Bisky detached the
curtain from it, and at this point she had the mast, boom and sail for her
FlounderCraft.

The FlounderCraft was fully disassembled and all of its parts were stowed
away in different and unlikely areas of the apartment. One of the drawers
underneath her bed contained the rudder and the keel.  The hull was
unrecognizable on its own, and enjoyed secrecy just by resting in the corner
by the kitchen window. The sail was actually a triangular lateen sail, but
it was so big that it only looked like a normal shower curtain from the
outside, as the third point was tucked into the bathtub. The only
components which remained were the tackle and other rigging gear, which was
also inconspicuous in Bisky's utility drawer.

The cover was never blown, but Bisky remembered a time when it got really,
really close. Petrus had come to visit, and he wondered what was that weird
board in the corner by kitchen window.

"`It's a, uh, it's going to become a new skateboard deck!`" she improvised.
It was a plausible explanation, and Petrus did see Bisky's actual skateboard
in another corner of the apartment, too.

"`It's going to require a _lot_ of work,`" Petrus said. "`It's nowhere near
the same size or shape as your skateboard.`"

"`Forest is gonna help me out,`" she lied. Forest was Gardenia's brother.

Finally, Petrus dropped it altogether. Bisky queued up one sigh of relief
for when he would eventually leave.

Essentially, the FlounderCraft was hidden in plain sight. And it finally was
time to take it out.

---

FlounderCraft were very small, very simple boats, essentially a dinghy with
a board-like hull and a lateen sail. They came in a kit, and ostensibly were
fun to assemble. But Bisky couldn't keep the box. Instead, she put all of
the parts inside of a duffel bag, flung it over her shoulder, and carried
the board all the way to the beach. The beach was a half-mile further away
from her apartment than merely going to the water's edge, because the
shipping docks had already occupied that area.
