== Chapter 3

There was only thing Bisky hated more than douchey preppy foxbros. And that
was her own alarm clock.

The idea was to be up at 6 o'clock, when the alarm went off, and then have a
whole hour to take a shower, put on clothes and makeup and fluff her tail,
be out the door at 7, arrive at Carmen's Coffee at 7:15, and then be
prepared for customers at 7:30. In practice, though, the alarm would wake
her up at 6, then she would lay in bed dazed and confused until 6:45, have
barely enough time to get ready, and then arrive at the café just minutes
before her shift. Today was one of _those_ days.

"`Hey, gang,`" Bisky announced as she entered the front door. The
super-early-morning regulars were already sitting in their regular seats
with their regular coffees with their regular pastries. Seemed just like the
good ole halcyon days of one week ago.

There already was quite a bit of a rush. Mondays. Joyce, the squirrel,
looked up and recognized Bisky from her station. She nodded and smiled
quickly in Bisky's direction before returning her attention to her current
customer.

Bisky went to the back room, quickly donned her brown apron and opened up
the station next to Joyce. She punched in a few numbers on the computer
screen from muscle memory and invited the next customer over. In the brief
moment where neither Joyce nor Bisky were in the process of helping a
customer, Joyce turned to Bisky and said: "`Happy Monday, Bisky. Feeling
alright?`"

"`Yes, thanks. I'll tell you at lunch.`"
