== Chapter x10 (in which bisky sails alone)

Bisky did not typically have mornings to herself, but she was going to make
the most out of this one. She prepared a simple breakfast: an almond muffin
from the family bakery, warmed up, sliced, and lightly dressed with honey
flavored with anise, with sliced mackerel on the side and a glass of lime
juice.

After quietly enjoying her meal, she proceeded to the bathroom, carrying her
chair with her. She confronted the shower curtain and stood her ground. It
showcased a simple design, featuring a single, large, stylized starfish atop
a field of white.  Bisky put the chair close to the shower and she stood on
it. And while on her pedestal, she closed her eyes, took a deep breath and
spoke as quietly she could: "`I'm so sorry, dad.`" 

Bisky squeezed her eyes tight and thrust her arm through the rod of the
shower curtain. It fell into the bathtub with a hard and unusually loud,
metallic _clank_. She hopped off the chair unplugged the rubber stop off of
one end of the rod. It contained several thinner rods, a far heavier and
sturdier one, for it was the reason behind that _clank_. Bisky detached the
curtain from it, and at this point she had the mast, boom and sail for her
FlounderCraft.

The FlounderCraft was fully disassembled and all of its parts were stowed
away in different and unlikely areas of the apartment. One of the drawers
underneath her bed contained the rudder and the keel.  The hull was
unrecognizable on its own, and enjoyed secrecy just by resting in the corner
by the kitchen window. The sail was actually a triangular lateen sail, but
it was so big that it only looked like a normal shower curtain from the
outside, as the third point was tucked into the bathtub. The only
components which remained were the tackle and other rigging gear, which was
also inconspicuous in Bisky's utility drawer.

The cover was never blown, but Bisky remembered a time when it got really,
really close. Petrus had come to visit, and he wondered what was that weird
board in the corner by kitchen window.

"`It's a, uh, it's going to become a new skateboard deck!`" she improvised.
It was a plausible explanation, and Petrus did see Bisky's actual skateboard
in another corner of the apartment, too.

"`It's going to require a _lot_ of work,`" Petrus said. "`It's nowhere near
the same size or shape as your skateboard.`"

"`Forest is gonna help me out,`" she lied. Forest was Gardenia's brother.

Finally, Petrus dropped it altogether. Bisky queued up one sigh of relief
for when he would eventually leave.

Essentially, the FlounderCraft was hidden in plain sight. And it finally was
time to take it out.

---

FlounderCraft were very small, very simple boats, essentially a dinghy with
a board-like hull and a lateen sail. They came in a kit, and ostensibly were
fun to assemble. But Bisky couldn't keep the box. Instead, she put all of
the parts inside of a duffel bag, flung it over her shoulder, and carried
the board all the way to the beach. The beach was a half-mile further away
from her apartment than merely going to the water's edge, because the
shipping docks had already occupied that area.

It was barely 10 o'clock and the unnamed beach was already rather crowded,
not because it was popular, but because it was super small. When most
animals thought of beaches in Port Sokuit, they did not think of the Cargo
District. They thought of the more touristy areas such as the boardwalk,
which was a pawful of miles south from where Bisky lived.

This would not be the FlounderCraft's maiden voyage. That happened four or
five years ago, when both of Bisky's parents spent a long weekend alone
together in the distant resort town of Roselle, not too far from where they
were born. They were celebrating their twenty-fifth year of marriage. Bisky
was supposed to have helped out in the bakery during that time, but instead
she assembled her FlounderCraft for the first time and took to the sea. She
didn't go very far, never past the outer limits of Sokuit Lagoon, but it was
the very first vessel that she had navigated herself. It didn't matter how
much of a toy the FlounderCraft was in comparison to _real_ boats. The point
was Bisky Damiat was _in control._

Four or five years later, Bisky finally had the opportunity to set sail
again. The water by the little municipal beach in the Cargo District was far
deeper than Sokuit Lagoon, and considerably rougher and colder. Basically,
this beach had no redeeming qualities. But she knew that the FlounderCraft
could handle it, and the winds were strong this morning.

There was virtually zero room left on the beach, since it was so small and
crowded, but that hardly mattered to Bisky because once the dinghy was
assembled, she would not be setting paw back onto the sand for the rest of
the day. The other animals and their pups were inconvenienced by Bisky's
construction project and her unwieldy tail, but she tried to reassure them
that she'd be done quickly. She was not kidding. Bisky, always the capable
engineer, assembled the boat in half the time it required most animals.
Within minutes, she had a little boat with the lateen sail properly rigged.
The stylized starfish on the field of white clearly appeared prouder and
more at home in this arrangement, instead of pretending to be some excuse
for a shower curtain.

And Bisky, whose heart pumped blood downriver towards the sea, who knew
exactly what she was doing, who knowingly caused her parents and every other
skunk ancestor to roll in their graves, embarked.

The choppiness of the waves were no match for the skunk's dexterous
manipulation of the sail. She wielded the ropes as if in a chariot driven by
a team of seahorses. The wind was somewhat erratic, intruding in brief gusts
whenever it felt like, but Bisky had already struck a deal with the Maker.
She could feel the wind before it came.

The FlounderCraft could really only fit one animal, or maybe one animal and
their kit, thus even the slightest movement of the sail seemed amplified. It
was rather easy to oversteer, especially if one were going as fast as Bisky
was. But Bisky's valiant mastery of the ropes and clever utilization of her
big, fluffy tail made for smooth sailing.

She was the only one sailing at this beach. It did not occur to her if any
of the several animals still on the shore thought it was just plain weird a
_skunk_ would be out in the water, let alone running downwind directly into
the wild blue. Skunks never belonged in the water. It was not a skunk's
place.  Well, maybe it wasn't _their_ place to judge her so.

She went as far as the first line of buoys, which were situated two hundred
yards away from the shore. With a small paddle, she rotated the boat into
the opposite direction and tied off the sail so that the craft remained
stationary.

The trek was already somewhat taxing for the little skunk, having tamed
waves that she should not have been able to tame. But a torrent of
adrenaline and sheer, pure joy sneakily kicked in and nearly threw her
overboard. Suddenly unsure of what exactly was going on, she decided let her
body and her brain do whatever it wanted. And her body and brain wanted
Bisky to stand up, face the distant city, and sing the song only skunks
exhilarated beyond recognition sing.

_Aaaaaaaiiiieeeee!!!_

The cry immediately depleted Bisky's fuel tank, and she lost her pawing, but
she instinctually grabbed onto the closet line and saved herself from
falling overboard yet again. She laughed boisterously at nothing, at
herself, at everything. After a moment to re-energize, she stood up and
faced the city again.

"`Listen up, you fishdicks!! I'm a daytime skunk! I'm a woman! I study
balhámotesse! I'm probably bisexual! I'm gonna sail in circles around all of
you one day!  And I'm _so alone_ in this world you don't have a fucking
clue!!`"

She turned around to face the open ocean, heaved a sigh of relief, then
resumed her confession to the city.

"`My parents are dead and I'm scared shitless! By the way, I'm so sorry,
dad! I really do love you! Anyway, I'm no good at anything!! I'm a shipwreck
and I'm desperate and I'm pleased to meet you and I just want to be your
friend.`"

A beat. Then, as quietly as she could: "`...but there's only enough room on
this boat for one.`" The bitterness of that last statement did not taste
good mixed with the salty air of the sea.

And just like that, despite having conquered the waves with such graceful
skill and finesse, Bisky felt defeated. She let herself drop to the deck,
but didn't have plans to get back up anytime soon. She sat there, hundreds
of yards away from the shore, swaying gently, and meditated. One contingent
of Bisky's brain wanted her to throw herself overboard. Another faction
believed in her captaining ability -- her capability to navigate the muddy,
temperamental and unknowable waters of her destiny.

"`There's only enough room on this boat for one,`" she repeated to herself.
She did not want to be okay with that. But right at that moment, she opened
her heart and every square inch of her indomitable yet frightened self to
the possibility that she might.
