== Chapter x12 (in which bisky and timo agree to go on a date)

_Some animals are just plain gross. They don't even care. They totally
forget that this space isn't just for them. But how could anybeast forget
that? And even if you did think this space was only for them, why would you
leave it so messy for yourself? It doesn't make any sense. Who can possibly
tolerate this? Have some dignity for yourself, even. Feral beasts, all of
them..._

Bisky ran all of these thoughts through herself as she dipped the mop into
the bucket and dragged it across the bathroom floor for what felt like the
hundredth time today. She looked up and saw all sorts of paw prints on the
wall near the toilet and the sink. _What are animals even doing in here?_
She considered mopping the walls, that's how gross Carmen's bathroom was
today.

Joyce's monotone voice reverberated brightly off of the walls, as nasty as
Bisky thought they were. "`Bisky, what's up, babe? You're taking forever in
there.`"

Bisky snorted. "`It was really gross in here. Do we need to get a bigger
trash can or something? Animals keep _missing_ it.`"

Joyce shrugged. "`Dunno. Some animals are just plain gross.`"

She raised an eyebrow when she saw Bisky smile and laugh.

"`You think that's funny?`"

"`Naw, Joyce, it's just, you took the words straight from my brain.`"

"`Heh. Actually, it's an intercranial device. I can hear the thoughts of
other animals who are on the same frequency as me.`"

Bisky snorted, her smile widened. Joyce, on the other paw, never smiled, and
her idiosyncratic variety of "`laughing`" had the capacity to make other
animals shift uncomfortably in their seats, but Bisky knew she was just
playing "`lightheartedly.`"

The bell on the door jingled, signaling the arrival of a new customer.

"`Seriously, babe. Wrap this up.`"

"`Aye aye!`"

Joyce looked over her shoulder and reacted audibly. Bisky understood that
meant she _really_ should get a move on, in order to see what her boss was
seeing.

And she was glad she did.

Right on schedule, Timo stood in line on early Thursday afternoon and was
contemplating the menu. He always ordered something different every time.
Bisky appreciated that it certainly kept things interesting, but there were
more important things going on. Timo was the fox with the gentle soul and
beacon of joy in Bisky's Thursday. Timo was the fox who reinvigorated
Bisky's belief in other animals. Timo was the fox who wore his heart in his
mind and his mind in his heart.

And it drove her insane, nearly to the point of losing control of her own
scent glands, that he was in fact a fox.

Bisky skipped to the register and waved like Gardenia did. She did not
notice the smirk sculpted on Joyce's face.

"`Hey hey, Bisky!`"

Bisky could only speak in smiles.

"`I'm truly glad to see you,`" Timo said earnestly. "`Feeling better?`"

Bisky nodded. "`Yes, thank you, Timo.`"

"`I've missed you,`" Timo said. "`Um, do you need to get back to cleaning?`"

"`No, I finished,`" Bisky said gently for some reason.

"`So that mop is just a fashion statement,`" Timo joked.

Bisky cranked her head slowly to the left to discover she was still in fact
holding the sopping mop. Her smile blossomed ever more sheepish, which was
impressive, considering she was not at all a sheep.

"`Ah, yup,`" Bisky broadcast through her stupid grin. "`This is an haute
couture walking mop.`"

Timo never laughed at others. He only laughed with them. "`Artisinally woven
mopping silk attached to the only the finest beechwood handle.`"

"`Yeah, canes are so last year, ha ha ha ha ha.`"

After Bisky decided she was drawing this moment out too long, she asked Timo
to wait just a second for her to put it back in the closet. He took that
opportunity to finalize his order.

Bisky returned to the register and laughed some residual laughs.
"`Seriously, dude, I'm alright. I feel a lot better. I think I can make it
through this.`"

"`That's excellent.`"

"`What can I get ya?`"

"`I want to get in the autumn mood... how about a pumpkin spice latte?`"  

Bisky secretly 
