== Chapter x9 (in which bisky steals a ship)

In retrospect, Bisky was the _perfect_ animal to pull it off. She was
knowledgeable about the specific vessel in question. She was mostly black
and could hide in the night easily. She lived rather close to the docks. She
needed the money. Too bad Bisky wasn't as nocturnal as most skunks usually
are.

She had attempted to get some rest -- even a little _nap_ for Balhámoté's
sake, or even the Maker's, she was so desperate -- before embarking on
this...  quest. Instead, she was constantly woken up by her heart, which was
beating as if a boxer were laying into it.

Her alarm went off. 2:30 AM. She shut it off immediately, hurriedly, out of
fear that her downstairs neighbors might hear it and then call the
authorities on her. She took a deep breath, as deep as the sea, and hopped
out of bed.

Bisky was cold. Autumn in the Cargo District in the middle of the night was
always pretty chilly. But Bisky felt frozen. She put on her oversized hoodie
even though she was prepared to burst like a water balloon full of sweat. 

She was desperate for ways to calm down. She considered taking a bite of the
cannabis gummy, but was afraid it would kick in at the perfectly wrong
moment. Cannabis had a way of sneaking in like that, in Bisky's experience.
Instead, she settled on a raspberry muffin from her father's -- er, her
uncle's -- bakery. She shook her head, somehow convinced she would never get
used to saying that, and then took a methodical, deliberate bite.  She
chewed as slowly as she could, and tried to think about the raspberry and
flax taste instead of what her father would think about _all of this._ He
would have been deathly ashamed, betrayed, then left behind and forgotten.

"`I'm so sorry, dad,`" Bisky whispered. A tear ran off her cheek and into
the half-eaten muffin. 

Eventually, she finished the muffin and changed into the blackest outfit she
could manage. BShe looked in the mirror, turned around, and fluffed her tail,
even though the occasion didn't seem to warrant a fluffy tail at all.
